# 

version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./contrib/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - tuber

  frontend:
    build: ./frontend
    image: magfest/tuber:latest-frontend
    ports:
      - "8000:8000"
    networks:
      - tuber

  backend:
    build: ./backend
    image: magfest/tuber:latest-backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://tuber:tuber@postgres/tuber
      REDIS_URL: redis://redis:6379/0
      VERBOSE: "true"
      FLASK_ENV: production
      WORKERS: 4
      CIRCUITBREAKER_THREADS: 4
    scale: 1
    networks:
      - tuber

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_PASSWORD: tuber
      POSTGRES_USER: tuber
      POSTGRES_DB: tuber
    ports:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - tuber

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - tuber

networks:
  tuber:

volumes:
  db-data:
