# 

version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./contrib/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - tuber

  tuber:
    build: ./
    environment:
      - FLASK_ENV=production
      - FORCE_HTTPS=false
      - STATIC_PATH=/app/dist
    ports:
      - "8080:8080"
    networks:
      - tuber

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - tuber

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - tuber

networks:
  tuber:

volumes:
  db-data:
