name: Python application

on:
  push:
    branches:
      - master

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install
      run: |
        make
    - name: Test with pytest
      run: |
        venv/bin/pip install pytest
        make test
  build_and_test_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Create venv
      run: |
        python -m venv venv
    - name: Install tuber
        venv\Scripts\activate && cd server && ..\venv\Scripts\python.exe setup.py develop
    - name: Test with pytest
      run: |
        venv\Scripts\pip.exe install pytest
        venv\Scripts\pytest.exe
        npm test:unit
        npm test:e2e