name: Python application

on:
  push:
    branches:
      - master

jobs:
  build_and_test_ubuntu:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install
      run: |
        make
    - name: Test with pytest
      run: |
        python -m pip install pytest
        make test
