name: Python application

on:
  push:
    branches:
      - master

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install
      run: |
        make
    - name: Test with pytest
      run: |
        venv/bin/pip install pytest
        make test
    - name: Build DEB
      run: |
        debuild -us -uc
  build_and_test_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Create venv
      run: |
        python -m venv venv
    - name: Install tuber
      run: |
        venv\Scripts\activate && cd server && ..\venv\Scripts\python.exe setup.py develop
    - name: Build Frontend
      run: |
        npm install
    - name: Run backend tests
      run: |
        venv\Scripts\pip.exe install pytest
        venv\Scripts\pytest.exe
    - name: Run frontend unit tests
      run: |
        npm run test:unit
    - name: Run frontend end to end tests
      run: |
        npm run test:e2e
    - name: Build MSI Installer
      run: |
        venv\Scripts\activate && cd server && ..\venv\Scripts\python.exe setup.py bdist_msi