name: Python application

on:
  push:
    branches:
      - master

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install
      run: |
        make
    - name: Test with pytest
      run: |
        venv/bin/pip install pytest
        make test
    - name: Build DEB
      run: |
        apt install debuild
        debuild -us -uc
  build_and_test_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Install
      run: |
        make
    - name: Test with pytest
      run: |
        venv/bin/pip install pytest
        make test
    - name: Build DMG
      run: |
        echo "Building DMG"