name: Backend - Run Tests

on:
  workflow_dispatch:
  push:
    paths:
    - 'backend/**'
    - '.github/workflows/ci-backend.yaml'
    - '.github/workflows/run-tests.yaml'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: "./backend"
          target: test
          load: true
          tags: ghcr.io/${{ github.repository }}-backend:latest

      - name: Run Tests
        run: docker compose run backend pytest