---
name: Backend - Run Tests

on:
  workflow_dispatch:
  push:
    paths:
    - 'backend/**'
    - '.github/workflows/ci-backend.yaml'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to GHCR
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: "./backend"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}-backend:testing
          labels: ${{ steps.meta.outputs.labels }}

- name: Run Tests
        run: docker compose run backend pytest