name: Backend - Run Tests

on:
  workflow_dispatch:
  push:
    paths:
    - 'backend/**'
    - '.github/workflows/ci-backend.yaml'
    - '.github/workflows/run-tests.yaml'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - id: lowercase-repo-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: "./backend"
          target: test
          load: true
          tags: ghcr.io/${{ steps.lowercase-repo-name.outputs.lowercase }}-backend:latest

      - name: Run Tests
        run: docker compose run backend pytest